apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-1
  labels:
    app: grafana-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grafana-1
  template:
    metadata:
      labels:
        app: grafana-1
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
